name: build
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: |
          pyinstaller --onefile --noconsole tray-timer.py
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: |
          ls -lR artifacts
          mv artifacts/build-ubuntu-latest/dist/tray-timer      tray-timer.linux.x86_64
          mv artifacts/build-windows-latest/dist/tray-timer.exe tray-timer.exe
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, "refs/tags/")
        with:
          files: |
            README.md
            COPYING
            tray-timer.linux.x86_64
            tray-timer.exe
            tray-timer.py
